# Generated by Django 4.1.3 on 2022-11-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('mobile_no', models.PositiveIntegerField(null=True)),
                ('surname', models.CharField(max_length=12)),
                ('other_name', models.CharField(max_length=12)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('village', models.CharField(max_length=12)),
                ('ward', models.CharField(choices=[('Thange', 'Thange'), ('Kikumbulyu South', 'Kikumbulyu South'), ('Kikumbulyu North', 'Kikumbulyu North'), ('Masongaleni', 'Masongaleni'), ('Nguumo', 'Nguumo'), ('Mtito Andei', 'Mtito Andei'), ('Ivingoni/Nzambani', 'Ivingoni/Nzambani'), ('Emali/Mulala', 'Emali/Mulala'), ('Makindu', 'Makindu'), ('Nguu/Masumba', 'Nguu/Masumba')], max_length=50, null=True)),
                ('pre_condition', models.CharField(choices=[('None', 'None'), ('HIV', 'HIV'), ('Down Syndrome', 'Down Syndrome'), ('Orofacial cleft', 'Orofacial cleft'), ('Hemophilia', 'Hemophilia'), ('Congenital dislocated hip', 'Congenital dislocated hip'), ('Tay-Sachs disease', 'Tay-Sachs disease')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_ID', models.PositiveIntegerField()),
                ('Surname', models.CharField(max_length=12)),
                ('Other_name', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=12, null=True)),
                ('DOB', models.DateTimeField()),
                ('Mobile_No', models.PositiveIntegerField()),
                ('Job_description', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.CharField(choices=[('BCG', 'BCG'), ('OPV ', 'OPV '), ('Rotavirus ', 'Rotavirus'), ('Pneumo_Conj', 'Pneumo_Conj '), ('DTWPHibHepB', 'DTWPHibHepB'), ('IPV', 'IPV'), ('YF', 'YF'), ('Measles', 'Measles '), ('HPV', 'HPV')], default='some_value', max_length=50)),
                ('mode_of_admission', models.CharField(choices=[('oral', 'oral'), ('injection', 'injection')], max_length=50, null=True)),
                ('batch_no', models.CharField(max_length=50)),
                ('vaccine_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('staff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('BCG', 'BCG'), ('OPV ', 'OPV '), ('Rotavirus ', 'Rotavirus'), ('Pneumo_Conj', 'Pneumo_Conj '), ('DTWPHibHepB', 'DTWPHibHepB'), ('IPV', 'IPV'), ('YF', 'YF'), ('Measles', 'Measles '), ('HPV', 'HPV')], max_length=50, null=True)),
                ('immunization_description', models.CharField(max_length=12, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vaccine_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_registration_no', models.CharField(max_length=50, null=True)),
                ('clinic_no', models.CharField(choices=[('clinic I', 'clinic I'), ('clinic II', 'clinic II'), ('clinic III', 'clinic III'), ('clinic IV', 'clinic IV'), ('clinic V', 'clinic V'), ('clinic VI', 'clinic VI'), ('clinic VII', 'clinic VII'), ('clinic VIII', 'clinic VIII'), ('clinic IX', 'clinic IX')], max_length=50, null=True)),
                ('weight', models.CharField(max_length=10, null=True)),
                ('height', models.CharField(max_length=10, null=True)),
                ('dose_no', models.CharField(choices=[('dose I', 'dose I'), ('dose II', 'dose II'), ('dose III', 'dose III')], max_length=50, null=True)),
                ('comment', models.CharField(max_length=12, null=True)),
                ('immunized_at', models.DateTimeField(null=True)),
                ('return_date', models.DateTimeField(null=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.parent')),
            ],
            options={
                'verbose_name_plural': 'Child',
            },
        ),
    ]
