# Generated by Django 4.1.3 on 2022-11-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_child_vaccine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
