# Generated by Django 4.1.3 on 2022-11-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_child_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.parent'),
        ),
    ]
