# Generated by Django 4.1.3 on 2022-11-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_child_parent_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name_plural': 'Parent'},
        ),
    ]
